version: "3"
services:
  site:
    build:
      context: .
      dockerfile: Dockerfile-site
    image: blog-site
    volumes:
      - ./_posts:/blog/_posts
    container_name: blog-site
    ports:
      - 8080:80

#  nginx:
#    build:
#      context: ./nginx
#      dockerfile: Dockerfile-nginx
#    image: blog-nginx
#    container_name: blog-nginx
#    volumes:
#      - /etc/blog_certs:/etc/nginx/certification
#      - /home/rlin/certs/letsencrypt/www:/var/www/letsencrypt
#      - /home/rlin/certs/letsencrypt/etc:/etc/letsencrypt
#    links:
#      - site:blog
#      - gitlab:gitlab
#    ports:
#      - 80:80
#      - 443:443

