version: "3"
services:
  site:
    build:
      context: .
      dockerfile: Dockerfile-site
    image: blog-site
    volumes:
      - ./_posts:/blog/_posts
    container_name: blog-site

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile-nginx
    image: blog-nginx
    container_name: blog-nginx
    volumes:
      - /etc/blog_certs:/etc/nginx/certification
    links:
      - site:blog
    ports:
      - 80:80
      - 443:443